version: '3.8'

services:

  nginx:
    build: 
      context: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 3002:80
    depends_on:
      - wsgi-web


  wsgi-web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    env_file:
      - ./.env
    depends_on:
      - db


  asgi-web:
    build: .
    command: python3 socketio_server.py
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    depends_on:
      - wsgi-web
      - db


  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  

volumes:
  postgres_data:
  static_volume: