version: '3.8'

services:

  nginx:
    build: 
      context: ./nginx
    ports:
      - 3002:80
    depends_on:
      - wsgi-web


  wsgi-web:
    build: .
    # command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db


  asgi-web:
    # image: daphneeu/daphne-dev:latest_X86-64_BASE
    build: .
    # command: make run-socket-server
    command: python3 socketio_server.py
    volumes:
      - ./:/usr/src/app/
    # ports:
    #   - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - wsgi-web
      - db


  db:
    image: postgres:15.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  

volumes:
  postgres_data:
